CREATE TABLE exchange_rates (
                      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      base_currency_id int REFERENCES currencies (id) ON DELETE CASCADE,
                      target_currency_id int REFERENCES currencies (id) ON DELETE CASCADE,
                      rate decimal(14,6) NOT NULL
);

CREATE UNIQUE INDEX idx_base_target ON exchange_rates (base_currency_id, target_currency_id);